Enable HA/Replication Slots
tembo-io/tembo-stacks pull request #213
Opened 2023-08-17 20:46 UTC by nhudson

This PR is meant to add the ability to enable HA/Replication Slots configuration into the Tembo Cloud stack.

* Adds new spec to `CoreDBSpec`: `TemboHighAvailability` is the new ENUM for configuring HA based workloads.  We can add to this later to figure out exactly how the HA parts need to be setup as we add more features to it.  For now we are just setting up replication slots like below:
```
spec:
  high_availability:
    enable_replication_slots: true
```

* We now respect the value of `replicas` and it will set the replica/instance count from `spec.replicas`
* Change `spec.replicas` from `i32` to `i64` as that is what is needed for `instances` inside `ClusterSpec`.
* Change the `topology_key` value to the correct one for EKS.  In the future we will need to add more here depending on the cloud environment.

Fixes: [TEM-1384](https://linear.app/tembo/issue/TEM-1384)

2023-08-17 21:29 UTC, sjmiller609 requested changes

2023-08-17 21:29 UTC, sjmiller609 commented on charts/tembo-operator/templates/crd.yaml
> +                type: object
Let's just pick what we think is best under the hood when replicas > 1 and not allow configuration of it in CoreDB spec, so we can remove this section

2023-08-17 21:29 UTC, sjmiller609 commented on charts/tembo-operator/templates/crd.yaml
> +                format: int64
Let's just type cast this in the operator instead of changing the crd, since the type is included in the CRD spec and I don't know exactly what happens to existing resources if that's changed - but could be convinced otherwise

2023-08-17 21:29 UTC, sjmiller609 commented on tembo-operator/src/cloudnativepg/cnpg.rs
> +                        enabled: Some(true),
https://github.com/cloudnative-pg/cloudnative-pg/pull/2601

2023-08-17 21:29 UTC, sjmiller609 commented on tembo-operator/tests/integration_tests.rs
> +    async fn functional_test_ha_cnpg() {
Can you please expand this test or add a different test to initially launch with replicas 1, assert looks good, then change replicas to 2 and do the rest

2023-08-17 21:29 UTC, sjmiller609 commented on tembo-operator/src/cloudnativepg/cnpg.rs
>              min_sync_replicas: Some(0),
👍

2023-08-17 21:29 UTC, sjmiller609 commented on tembo-operator/src/cloudnativepg/cnpg.rs
> +                        enabled: Some(true),
When I check the CRD in our cluster, the default is false.
```
              replicationSlots:
                description: Replication slots management configuration
                properties:
                  highAvailability:
                    description: Replication slots for high availability configuration
                    properties:
                      enabled:
                        default: false
```

The helm chart is not updated to match the docs https://github.com/cloudnative-pg/charts/blob/39c99bc63cb2f97e2d2895484da2bbec0ee6c71f/charts/cloudnative-pg/templates/crds/crds.yaml#L3154

I am concerned because there is a note that this can only be enabled at creation time of the cluster

2023-08-17 21:29 UTC, sjmiller609 commented on tembo-operator/src/cloudnativepg/cnpg.rs
> +                        enabled: Some(true),
I'm not sure what should be done about that yet, but we should check in on this case where it's set to false, then we switch it to true on version 1.20 (which we already have) - maybe the docs are out of date, I'm not sure what would happen.

The ideal fix would be CNPG helm chart and docs updated to the correct status, then we don't specify this in our clusters, since it's just using the default configuration.

2023-08-17 21:38 UTC, nhudson commented on tembo-operator/src/cloudnativepg/cnpg.rs
> +                topology_key: Some("failure-domain.beta.kubernetes.io/zone".to_string()),
Weird I didn't yesterday when I looked. If so then we can change it back

2023-08-17 21:49 UTC, nhudson commented on tembo-operator/src/cloudnativepg/cnpg.rs
>              min_sync_replicas: Some(0),
This is an async replication configuration. If we ever want to enable synchronous replication, then we will need to do some calculations around how many replicas are set.

2023-08-17 21:51 UTC, nhudson commented on tembo-operator/src/cloudnativepg/cnpg.rs
> +                        enabled: Some(true),
Not really sure what the issue is here. The default is false. I do believe from reading the docs if you set replicas to 2 it will enable this automatically unless you specifically tell it not to. I didn't test that scenario since we would always want this enabled if the cluster is in HA mode .

2023-08-17 21:53 UTC, sjmiller609 commented on tembo-operator/src/cloudnativepg/cnpg.rs
>              min_sync_replicas: Some(0),
Ok sounds good. I prefer async and think it makes sense for what HA is supposed to do (increase SLA), maybe some customers in the future want sync for their use case (extreme durability requirement in comparison to performance and availability)

2023-08-17 21:56 UTC, sjmiller609 commented on tembo-operator/src/cloudnativepg/cnpg.rs
> +                        enabled: Some(true),
I mean since it's currently default false, and we already have clusters deployed, we are trying to switch them to true, but the feature has a note that it's only allowed to be set at creation

https://cloudnative-pg.io/documentation/1.20/api_reference/#ReplicationSlotsHAConfiguration

> This can only be set at creation time.

2023-08-17 21:58 UTC, nhudson commented on tembo-operator/src/cloudnativepg/cnpg.rs
> +                        enabled: Some(true),
I would say that is wrong then since I am able to set it and update it to HA from a single instance that was already created. 

Maybe it's true for CNPG operator version <1.20 since this is a new feature in 1.20?

2023-08-17 22:16 UTC, sjmiller609 commented on tembo-operator/src/cloudnativepg/cnpg.rs
> +                        enabled: Some(true),
Ok that is what I’m hoping is the case, you should mention that in the cnpg PR

2023-08-17 23:49 UTC, nhudson commented on tembo-operator/tests/integration_tests.rs
> +    async fn functional_test_ha_cnpg() {
Added a test to launch a single instance and then update it to run with 2 replicas.

2023-08-17 23:49 UTC, nhudson commented on charts/tembo-operator/templates/crd.yaml
> +                type: object
This has been reverted.

2023-08-17 23:50 UTC, nhudson commented on tembo-operator/src/cloudnativepg/cnpg.rs
> +                topology_key: Some("failure-domain.beta.kubernetes.io/zone".to_string()),
reverted

2023-08-18 13:56 UTC, sjmiller609 approved these changes
Looks good!

Can you please QA this situation in dev:

Launch new instance, enable HA, then disable HA (this will move the replication slots management from false -> true -> false). Check if replication slots are managed (removed), i.e. checking they are not just filling up the replication slot. Since if the replication slots are not removed, then they will fill up and cause disk to fill up

2023-08-18 14:29 UTC, nhudson commented
> Looks good! I think OK to merge if tests pass, but needs some special attention in dev cluster QA.
> 
> Can you please QA this situation in dev:
> 
> Launch new instance, enable HA, check replication slots are created. Then disable HA (this will move the replication slots management from false -> true -> false). Check if replication slots are managed (removed), i.e. checking they are not just filling up the replication slot. Since if the replication slots are not removed, then they will fill up and cause disk to fill up

I am looking into the failing test now.  

For your scenario @sjmiller609, if you disable HA (set replicas to 1), it removes the replication slots entry from the table
```
postgres=# SELECT * FROM pg_replication_slots;
 slot_name | plugin | slot_type | datoid | database | temporary | active | active_pid | xmin | catalog_xmin | restart_lsn | confirmed_flush_lsn | wal_status | safe_wal_size | two_phase 
-----------+--------+-----------+--------+----------+-----------+--------+------------+------+--------------+-------------+---------------------+------------+---------------+-----------
(0 rows)
```

2023-08-18 16:55 UTC, merged