set `restartedAt` and `status.running` correctly
tembo-io/tembo-stacks pull request #270
Opened 2023-09-21 20:16 UTC by vrmiguel

2023-09-22 15:40 UTC, sjmiller609 requested changes
Nicely done!! A couple of small changes requested.

2023-09-22 15:40 UTC, sjmiller609 commented on conductor/src/lib.rs
> +async fn patch_merge_cdb_status(
this function already exists in controller.rs and is called
```
patch_cdb_status_merge
```

2023-09-22 15:40 UTC, sjmiller609 commented on tembo-operator/src/cloudnativepg/cnpg.rs
> +    }
Here, I think we check if we are updating it to a different value, if so we set running to false on coredb

2023-09-22 15:40 UTC, sjmiller609 commented on tembo-operator/src/extensions/database_queries.rs
> +            tracing::error!("Failed to deserialize DateTime from `restartedAt`: {err}");
Can you please include cdb name in the log

2023-09-22 15:40 UTC, sjmiller609 commented on tembo-operator/src/extensions/database_queries.rs
> +        .unwrap();
Please handle stdout as None with unexpected error, long requeue

2023-09-22 16:48 UTC, ianstanton reviewed
@vrmiguel Nicely done :tada: Can you add a test for this behavior in `tests/integration_tests.rs`?

2023-09-22 20:16 UTC, vrmiguel commented on tembo-operator/src/cloudnativepg/cnpg.rs
> +    }
Set running to false on `CoreDB` as in `cdb.running = false` ?

2023-09-22 20:17 UTC, vrmiguel commented on tembo-operator/src/cloudnativepg/cnpg.rs
> +    }
As in

```rust
    if let Some(restarted_at) = cdb.annotations().get(RESTARTED_AT) {
        match existing_restarted_at_annotation {
            Some(timestamp) if timestamp == restarted_at => {}
            Some(_) | None => {
                // Forward the `restartedAt` annotation from CoreDB over to the CNPG cluster
                let mut cluster_annotations = cluster.metadata.annotations.unwrap_or_default();
                cluster_annotations.insert(RESTARTED_AT.into(), restarted_at.to_owned());
                drop(restarted_at);

                if let Some(status) = &mut cdb.status {
                    status.running = false;
                }

                cluster.metadata.annotations = Some(cluster_annotations);
            }
        }
    }

```

2023-09-22 20:30 UTC, sjmiller609 commented on tembo-operator/src/cloudnativepg/cnpg.rs
> +    }
In this block, I think either remember the annotation it was before the update or set a bool like restart_annotation_updated. Then down below in this function reconcile_cnpg, using that information we know if we have updated the Cluster with a new annotation. If we did, right after we update it ...
```
    let _o = cluster_api
        .patch(&name, &ps, &Patch::Apply(&cluster))
```

Then, call to patch cdb status like that function patch_merge_cdb_status. This will call kubernetes API to set cdb.status.running to false - we do this because we just detected that we are initiating a restart

2023-09-25 15:49 UTC, sjmiller609 approved these changes
Add a test or add to an existing test, like Ian has suggested, then I think it's good to go!

2023-09-27 21:19 UTC, sjmiller609 approved these changes

2023-09-27 22:36 UTC, ianstanton approved these changes
:tada: Nicely done!

2023-09-28 01:13 UTC, merged