[tembo-operator] Reconcile Extensions into restored instance
tembo-io/tembo-stacks pull request #303
Opened 2023-10-03 02:12 UTC by nhudson

The PR finishes the PITR work for the operator.

2023-10-03 02:14 UTC, nhudson commented on tembo-operator/src/cloudnativepg/clusters.rs
> +#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
This is needed to evaluate and compare fields in `ClusterStatusConditionsStatus`

2023-10-03 02:16 UTC, nhudson commented on tembo-operator/src/controller.rs
> +                        Ok(None) | Err(_) => CoreDBStatus {
I am not really sure what I am supposed to put here.  If anyone has better suggestions please let me know.

2023-10-03 02:17 UTC, nhudson commented on tembo-operator/src/controller.rs
> +                                .and_then(|f| f.first_recoverability_time),
I am not really sure how else I am supposed to handle the `None` and `Err` matches for this.  If anyone has suggestions, please let me know.

2023-10-04 14:31 UTC, nhudson commented on tembo-operator/tests/integration_tests.rs
> +            let started_waiting = Utc::now();
@ianstanton I know you're at PGConf this week, but wanted to make you aware that I changed this up a bit  to be a bit more resilient when tests are run.

2023-10-04 14:31 UTC, nhudson commented on tembo-operator/tests/integration_tests.rs
> +            panic!("Status was not populated fast enough");
@ianstanton I know you're at PGConf this week, but wanted to make you aware that I changed this up a bit to be a bit more resilient when tests are run.

2023-10-04 15:03 UTC, sjmiller609 requested changes

2023-10-04 15:03 UTC, sjmiller609 commented on tembo-operator/src/extensions/install.rs
> +        return Err(true);
I think this change looks unnecessary because it's adding new flow control inside a logging statement, and because cdb.exec which is called below will raise Err in the case that pod is not up and that should handle this case

2023-10-04 15:52 UTC, nhudson commented on tembo-operator/src/cloudnativepg/cnpg.rs
> +}
Yeah I thought it was deleted with a rebase, but looks like it wasn't

2023-10-04 17:51 UTC, nhudson commented on tembo-operator/src/extensions/install.rs
> +        return Err(true);
The issue here is that without the return, it will attempt to install extensions in a pod that doesn't exist yet and error.  If you feel like it  should error in 100% of the situation then, sure lets take this out.  I don't see the need to log and error when it's attempting to restore an HA instance.

2023-10-16 15:29 UTC, sjmiller609 approved these changes

2023-10-16 15:37 UTC, merged